name: Skylife
version: '1.0-SNAPSHOT'
main: com.carinaschoppe.skylife.Skylife
api-version: '1.21'
description: Skylife is a Skywars Main-System Plugin used for a remake of Smash and Skywars
author: [ Carina Sophie Schoppe, Ceye4n ]
commands:
  start:
    description: Quickstarts a game
    usage: /start
    aliases: [ ]
  join:
    description: Joins a game specify if youve got premium
    usage: /join
    aliases: [ ]
  vanish:
    description: Vanishes a Player or makes them visible
    usage: /vanish
    aliases: [ v ]
  join:
    description: Joins a game specify if youve got premium
    usage: /join
    aliases: [ ]
  join:
    description: Joins a game specify if youve got premium
    usage: /join
    aliases: [ ]