name: Skylife
version: '1.0-SNAPSHOT'
main: com.carinaschoppe.skylife.Skylife
api-version: '1.21'
description: Skylife is a Skywars Main-System Plugin used for a remake of Smash and Skywars
author: [ Carina Sophie Schoppe (LazarusDE), Ceye4n ]
commands:
  start:
    description: Quickstarts a game
    aliases: [ s ]
  join:
    description: Joins a game specify if youve got premium
    aliases: [ ]
  leave:
    description: Leave the current game and go back to the lobby
    aliases: [ l, hub, spawn, lobby, back ]
  playeramount:
    description: Capable of setting the required amount of players for a game
    aliases: [ pm ]
  setlocation:
    description: Capable of setting up the locations for a game
    aliases: [ sl ]
  game:
    description: Capable of creating a game
    aliases: [ ]
  stats:
    description: Shows the stats of a player or of yourself
    aliases: [ stat ]
  overview:
    description: Shows an inventory with a list of games to play
    aliases: [ ov, games ]
  skills:
    description: Shows an inventory with a list of the possible skills in form of clickable items
    aliases: [ s, skill ]